development:
  adapter: postgresql
  encoding: UTF-8
  database: demo_app_development
  pool: 5
  username: postgres
  password: a+123456

test:
  adapter: postgresql
  encoding: UTF-8
  database: demo_app_test
  pool: 5
  username: postgres
  password: a+123456