 
development:
 adapter: postgresql
 encoding: unicode
 database: demo_app_development
 pool: 5
 username: postgres
 password: a+123456
test:
 adapter: postgresql
 encoding: unicode
 database: demo_app_test
 pool: 5
 username: postgres
 password: a+123456

production:
 adapter: postgresql
 encoding: unicode
 database: mydb_production
 pool: 5
 username: postgres
 password: a+123456